
/**************************************************************************
 *                                                                        *
 *  Regina - A Normal Surface Theory Calculator                           *
 *  CORBA Interface Definition                                            *
 *                                                                        *
 *  Copyright (c) 1999-2002, Ben Burton                                   *
 *  For further details contact Ben Burton (benb@acm.org).                *
 *                                                                        *
 *  This program is free software; you can redistribute it and/or         *
 *  modify it under the terms of the GNU General Public License as        *
 *  published by the Free Software Foundation; either version 2 of the    *
 *  License, or (at your option) any later version.                       *
 *                                                                        *
 *  This program is distributed in the hope that it will be useful, but   *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *  General Public License for more details.                              *
 *                                                                        *
 *  You should have received a copy of the GNU General Public             *
 *  License along with this program; if not, write to the Free            *
 *  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,        *
 *  MA 02111-1307, USA.                                                   *
 *                                                                        *
 **************************************************************************/

/* end stub */

#ifndef __NSCRIPT_IDL
#define __NSCRIPT_IDL

#include "Packet/NPacket.idl"

module Regina {
    module Packet {
        interface NScript : NPacket {
            long getNumberOfLines();
            string getLine(in long index);

            void addFirst(in string line);
            void addLast(in string line);
            void insertAtPosition(in string line, in long index);
            void replaceAtPosition(in string line, in long index);
            void removeLineAt(in long index);
            void removeAllLines();

            long getNumberOfVariables();
            string getVariableName(in long index);
            string getVariableValue_long(in long index);
            string getVariableValue_string(in string name);
            long getVariableIndex(in string name);

            void addVariable(in string name, in string value);
            void removeVariableAt(in long index);
            void removeVariable(in string name);
            void removeAllVariables();
        };
    };
};

#endif

