
/**************************************************************************
 *                                                                        *
 *  Regina - A Normal Surface Theory Calculator                           *
 *  CORBA Interface Definition                                            *
 *                                                                        *
 *  Copyright (c) 1999-2001, Ben Burton                                   *
 *  For further details contact Ben Burton (benb@acm.org).                *
 *                                                                        *
 *  This program is free software; you can redistribute it and/or         *
 *  modify it under the terms of the GNU General Public License as        *
 *  published by the Free Software Foundation; either version 2 of the    *
 *  License, or (at your option) any later version.                       *
 *                                                                        *
 *  This program is distributed in the hope that it will be useful, but   *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *  General Public License for more details.                              *
 *                                                                        *
 *  You should have received a copy of the GNU General Public             *
 *  License along with this program; if not, write to the Free            *
 *  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,        *
 *  MA 02111-1307, USA.                                                   *
 *                                                                        *
 **************************************************************************/

/* end stub */

#ifndef __NRANDOMACCESSRESOURCE_IDL
#define __NRANDOMACCESSRESOURCE_IDL

/**
 * This class is designed to allow the CORBA server access to remote
 * resources.  It used in the reverse direction as compared to most
 * of Regina's CORBA classes.
 *
 * Class NFile in the CORBA server should use this class as a client.
 * The user interface should provide an approprate servant implementation
 * of NRandomAccessResource to pass to NFile for reading and writing.
 */
module Regina {
    module File {
        interface NRandomAccessResource {
            boolean openRead();
            boolean openWrite();
            void close();
            long getOpenMode();

            char getChar();
            void putChar(in char c);
            long getPosition();
            void setPosition(in long pos);
        };
    };
};

#endif

