
/**************************************************************************
 *                                                                        *
 *  Regina - A Normal Surface Theory Calculator                           *
 *  Python Interface                                                      *
 *                                                                        *
 *  Copyright (c) 1999-2026, Ben Burton                                   *
 *  For further details contact Ben Burton (bab@debian.org).              *
 *                                                                        *
 *  This program is free software; you can redistribute it and/or         *
 *  modify it under the terms of the GNU General Public License as        *
 *  published by the Free Software Foundation; either version 2 of the    *
 *  License, or (at your option) any later version.                       *
 *                                                                        *
 *  As an exception, when this program is distributed through (i) the     *
 *  App Store by Apple Inc.; (ii) the Mac App Store by Apple Inc.; or     *
 *  (iii) Google Play by Google Inc., then that store may impose any      *
 *  digital rights management, device limits and/or redistribution        *
 *  restrictions that are required by its terms of service.               *
 *                                                                        *
 *  This program is distributed in the hope that it will be useful, but   *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *  General Public License for more details.                              *
 *                                                                        *
 *  You should have received a copy of the GNU General Public License     *
 *  along with this program. If not, see <https://www.gnu.org/licenses/>. *
 *                                                                        *
 **************************************************************************/

/**
 * Here we include _every_ available docstring header.
 *
 * The intent here is to ensure that we do not redefine the same docstring
 * constant in different ways within different headers.  (This could be a
 * risk, for example, when adding docstrings for overloaded global functions.)
 *
 * This list of includes could easily become out-of-date; we should go to some
 * effort periodically to ensure that all docstring headers are in fact
 * included here.
 */

#include "../docstrings/algebra/abeliangroup.h"
#include "../docstrings/algebra/grouppresentation.h"
#include "../docstrings/algebra/homgrouppresentation.h"
#include "../docstrings/algebra/intersectionform.h"
#include "../docstrings/algebra/markedabeliangroup.h"
#include "../docstrings/angle/angleflags.h"
#include "../docstrings/angle/anglestructure.h"
#include "../docstrings/angle/anglestructures.h"
#include "../docstrings/census/census.h"
#include "../docstrings/census/gluingperms.h"
#include "../docstrings/census/gluingpermsearcher.h"
#include "../docstrings/census/gluingpermsearcher2.h"
#include "../docstrings/census/gluingpermsearcher3.h"
#include "../docstrings/census/gluingpermsearcher4.h"
#include "../docstrings/census/purgeflags.h"
#include "../docstrings/concepts/array.h"
#include "../docstrings/concepts/core.h"
#include "../docstrings/concepts/io.h"
#include "../docstrings/concepts/iterator.h"
#include "../docstrings/concepts/maths.h"
#include "../docstrings/core/engine.h"
#include "../docstrings/core/output.h"
#include "../docstrings/core/regina-core.h"
#include "../docstrings/enumerate/doubledescription.h"
#include "../docstrings/enumerate/hilbertcd.h"
#include "../docstrings/enumerate/hilbertdual.h"
#include "../docstrings/enumerate/hilbertprimal.h"
#include "../docstrings/enumerate/maxadmissible.h"
#include "../docstrings/enumerate/ordering.h"
#include "../docstrings/enumerate/treeconstraint.h"
#include "../docstrings/enumerate/treelp.h"
#include "../docstrings/enumerate/treetraversal.h"
#include "../docstrings/enumerate/typetrie.h"
#include "../docstrings/enumerate/validityconstraints.h"
#include "../docstrings/file/fileformat.h"
#include "../docstrings/file/fileinfo.h"
#include "../docstrings/file/globaldirs.h"
#include "../docstrings/foreign/dehydration.h"
#include "../docstrings/foreign/isosig.h"
#include "../docstrings/foreign/orb.h"
#include "../docstrings/foreign/siglist.h"
#include "../docstrings/hypersurface/hypercoords.h"
#include "../docstrings/hypersurface/hyperflags.h"
#include "../docstrings/hypersurface/normalhypersurface.h"
#include "../docstrings/hypersurface/normalhypersurfaces.h"
#include "../docstrings/link/examplelink.h"
#include "../docstrings/link/link.h"
#include "../docstrings/link/linksig.h"
#include "../docstrings/link/modellinkgraph.h"
#include "../docstrings/link/spatiallink.h"
#include "../docstrings/link/tangle.h"
#include "../docstrings/manifold/graphloop.h"
#include "../docstrings/manifold/graphpair.h"
#include "../docstrings/manifold/graphtriple.h"
#include "../docstrings/manifold/handlebody.h"
#include "../docstrings/manifold/lensspace.h"
#include "../docstrings/manifold/manifold.h"
#include "../docstrings/manifold/sfs.h"
#include "../docstrings/manifold/sfsalt.h"
#include "../docstrings/manifold/simplesurfacebundle.h"
#include "../docstrings/manifold/snappeacensusmfd.h"
#include "../docstrings/manifold/torusbundle.h"
#include "../docstrings/maths/3d.h"
#include "../docstrings/maths/arrow.h"
#include "../docstrings/maths/binom.h"
#include "../docstrings/maths/cyclotomic.h"
#include "../docstrings/maths/forward.h"
#include "../docstrings/maths/integer.h"
#include "../docstrings/maths/laurent.h"
#include "../docstrings/maths/laurent2.h"
#include "../docstrings/maths/matrix.h"
#include "../docstrings/maths/matrix2.h"
#include "../docstrings/maths/matrixops.h"
#include "../docstrings/maths/numbertheory.h"
#include "../docstrings/maths/perm.h"
#include "../docstrings/maths/perm2.h"
#include "../docstrings/maths/perm3.h"
#include "../docstrings/maths/perm4.h"
#include "../docstrings/maths/perm5.h"
#include "../docstrings/maths/perm6.h"
#include "../docstrings/maths/perm7.h"
#include "../docstrings/maths/permgroup.h"
#include "../docstrings/maths/permsn.h"
#include "../docstrings/maths/polynomial.h"
#include "../docstrings/maths/primes.h"
#include "../docstrings/maths/rational.h"
#include "../docstrings/maths/ring.h"
#include "../docstrings/maths/vector.h"
#include "../docstrings/packet/attachment.h"
#include "../docstrings/packet/container.h"
#include "../docstrings/packet/packet.h"
#include "../docstrings/packet/packettype.h"
#include "../docstrings/packet/script.h"
#include "../docstrings/packet/text.h"
#include "../docstrings/progress/progresstracker.h"
#include "../docstrings/python/equality.h"
#include "../docstrings/snappea/examplesnappea.h"
#include "../docstrings/snappea/snappeatriangulation.h"
#include "../docstrings/split/sigcensus.h"
#include "../docstrings/split/sigisomorphism.h"
#include "../docstrings/split/signature.h"
#include "../docstrings/subcomplex/augtrisolidtorus.h"
#include "../docstrings/subcomplex/blockedsfs.h"
#include "../docstrings/subcomplex/blockedsfsloop.h"
#include "../docstrings/subcomplex/blockedsfspair.h"
#include "../docstrings/subcomplex/blockedsfstriple.h"
#include "../docstrings/subcomplex/layeredchain.h"
#include "../docstrings/subcomplex/layeredchainpair.h"
#include "../docstrings/subcomplex/layeredlensspace.h"
#include "../docstrings/subcomplex/layeredloop.h"
#include "../docstrings/subcomplex/layeredsolidtorus.h"
#include "../docstrings/subcomplex/layeredtorusbundle.h"
#include "../docstrings/subcomplex/layering.h"
#include "../docstrings/subcomplex/pillowtwosphere.h"
#include "../docstrings/subcomplex/pluggedtorusbundle.h"
#include "../docstrings/subcomplex/plugtrisolidtorus.h"
#include "../docstrings/subcomplex/satannulus.h"
#include "../docstrings/subcomplex/satblock.h"
#include "../docstrings/subcomplex/satblocktypes.h"
#include "../docstrings/subcomplex/satregion.h"
#include "../docstrings/subcomplex/snappeacensustri.h"
#include "../docstrings/subcomplex/snappedball.h"
#include "../docstrings/subcomplex/snappedtwosphere.h"
#include "../docstrings/subcomplex/spiralsolidtorus.h"
#include "../docstrings/subcomplex/standardsubcomplex.h"
#include "../docstrings/subcomplex/trisolidtorus.h"
#include "../docstrings/subcomplex/trivialtri.h"
#include "../docstrings/subcomplex/txicore.h"
#include "../docstrings/surface/disc.h"
#include "../docstrings/surface/disctype.h"
#include "../docstrings/surface/normalcoords.h"
#include "../docstrings/surface/normalflags.h"
#include "../docstrings/surface/normalsurface.h"
#include "../docstrings/surface/normalsurfaces.h"
#include "../docstrings/surface/prism.h"
#include "../docstrings/surface/surfacefilter.h"
#include "../docstrings/surface/surfacefiltertype.h"
#include "../docstrings/treewidth/treedecomposition.h"
#include "../docstrings/triangulation/alias/face.h"
#include "../docstrings/triangulation/alias/facenumber.h"
#include "../docstrings/triangulation/alias/isomorphism.h"
#include "../docstrings/triangulation/cut.h"
#include "../docstrings/triangulation/detail/boundarycomponent.h"
#include "../docstrings/triangulation/detail/component.h"
#include "../docstrings/triangulation/detail/example.h"
#include "../docstrings/triangulation/detail/face.h"
#include "../docstrings/triangulation/detail/facetpairing.h"
#include "../docstrings/triangulation/detail/simplex.h"
#include "../docstrings/triangulation/detail/strings.h"
#include "../docstrings/triangulation/dim2/component2.h"
#include "../docstrings/triangulation/dim2/triangle2.h"
#include "../docstrings/triangulation/dim2/triangulation2.h"
#include "../docstrings/triangulation/dim3/component3.h"
#include "../docstrings/triangulation/dim3/edge3.h"
#include "../docstrings/triangulation/dim3/homologicaldata.h"
#include "../docstrings/triangulation/dim3/tetrahedron3.h"
#include "../docstrings/triangulation/dim3/triangle3.h"
#include "../docstrings/triangulation/dim3/triangulation3.h"
#include "../docstrings/triangulation/dim3/vertex3.h"
#include "../docstrings/triangulation/dim4/component4.h"
#include "../docstrings/triangulation/dim4/edge4.h"
#include "../docstrings/triangulation/dim4/pentachoron4.h"
#include "../docstrings/triangulation/dim4/tetrahedron4.h"
#include "../docstrings/triangulation/dim4/triangle4.h"
#include "../docstrings/triangulation/dim4/triangulation4.h"
#include "../docstrings/triangulation/dim4/vertex4.h"
#include "../docstrings/triangulation/example.h"
#include "../docstrings/triangulation/example2.h"
#include "../docstrings/triangulation/example3.h"
#include "../docstrings/triangulation/example4.h"
#include "../docstrings/triangulation/facenumbering.h"
#include "../docstrings/triangulation/facepair.h"
#include "../docstrings/triangulation/facetpairing3.h"
#include "../docstrings/triangulation/facetspec.h"
#include "../docstrings/triangulation/isomorphism.h"
#include "../docstrings/triangulation/isosig.h"
#include "../docstrings/triangulation/triangulation.h"
#include "../docstrings/utilities/aggregator.h"
#include "../docstrings/utilities/base64.h"
#include "../docstrings/utilities/bitmanip.h"
#include "../docstrings/utilities/bitmask.h"
#include "../docstrings/utilities/boolset.h"
#include "../docstrings/utilities/bytesequence.h"
#include "../docstrings/utilities/exception.h"
#include "../docstrings/utilities/fixedarray.h"
#include "../docstrings/utilities/flags.h"
#include "../docstrings/utilities/i18nutils.h"
#include "../docstrings/utilities/intutils.h"
#include "../docstrings/utilities/listview.h"
#include "../docstrings/utilities/osutils.h"
#include "../docstrings/utilities/qitmask.h"
#include "../docstrings/utilities/randutils.h"
#include "../docstrings/utilities/sigutils.h"
#include "../docstrings/utilities/snapshot.h"
#include "../docstrings/utilities/stringutils.h"
#include "../docstrings/utilities/tableview.h"
#include "../docstrings/utilities/tightencoding.h"
#include "../docstrings/utilities/trieset.h"
#include "../docstrings/utilities/xmlutils.h"

int main() {
    return 0;
}

