#!/bin/sh

# Put us in the base Regina directory.
cd `dirname $0`

export options=runtime.opt
export regconf=regconf
export command=regina.cmd

# Check that there is a runtime configuration file.
if [ ! -f $options ]; then
	echo
	echo "######################################"
	echo "#                                    #"
	echo "#               REGINA               #"
	echo "#                                    #"
	echo "#  Runtime options cannot be found!  #"
	echo "#                                    #"
	echo "######################################"
	echo
	echo "There is no runtime options file $options."
	echo "You should run the RegConf configuration utility \"$regconf\","
	echo "    found in the base Regina directory ($PWD)."
	echo "I will try to do this now."
	echo
	if $regconf; then
		echo
		echo "Now that you have set the runtime options, try running this" \
			"program again."
		echo
	fi
	exit 1
else
	# Read in the options file.
	. $options

	# Run the application.
	if ! $Java "-Djava.library.path=$JNIDir" -cp "$JavaUI:$JavaJNI:$JavaCORBA:$DocJar:$BTools:$JPython:$JavaHelp:$ExtraClasses" normal.Application $@ ; then
		echo
		echo "################################"
		echo "#                              #"
		echo "#            REGINA            #"
		echo "#                              #"
		echo "#  Could not run application!  #"
		echo "#                              #"
		echo "################################"
		echo
		echo "An error occurred whilst trying to run the application."
		echo "The command used was:"
		echo
		echo "    $Java \"-Djava.library.path=$JNIDir\" -cp \"$JavaUI:$JavaJNI:$JavaCORBA:$DocJar:$BTools:$JPython:$JavaHelp:$ExtraClasses\" normal.Application $@"
		echo
		echo "The runtime options are set as follows:"
		echo
		echo "    Location of regina.jar: $JavaUI"
		echo "    Location of regina-jni.jar: $JavaJNI"
		echo "    Location of regina-corba.jar: $JavaCORBA"
		echo "    Location of regina-docs.jar: $DocJar"
		echo "    Java command: $Java"
		echo
		echo "    Engine directory: $JNIDir"
		echo
		echo "    Location of btools.jar: $BTools"
		echo "    Location of jpython.jar: $JPython"
		echo "    Location of jh.jar: $JavaHelp"
		echo "    Extra classes: $ExtraClasses"
		echo
		echo "Check that these options are correct and if necessary run the"
		echo "RegConf configuration utility \"$regconf\", found in the base"
		echo "Regina directory ($PWD)."
		echo
		exit 1
	fi
fi

