#!/bin/bash

# Enable job control, so that the final 'fg' does what it should.
set -m

arch=`uname -m`
os=`cat /etc/issue`

# Find a free display number.
for i in `seq 100`; do
	if [ ! -e "/tmp/.X$i-lock" ]; then break; fi
	i=$(($i+1))
done
if [ -e "/tmp/.X$i-lock" ]; then
	echo "ERROR: Could not find a free display number."
	echo "       Try removing some stale X lock files from /tmp."
	exit 1
fi

USE=:$i
echo "Using display $USE."

case "$os" in
	Ubuntu\ 6.06* )
		distro=Dapper
		;;
	Ubuntu\ 7.04* )
		distro=Feisty
		;;
	Ubuntu\ 7.10* )
		distro=Gutsy
		;;
	* )
		distro=Unknown
		;;
esac

#if [ "$distro" = Dapper -a "$arch" = x86_64 ]; then
#	type=xnest
#else
#	type=xephyr
#fi

# Always use Xnest for now; xephyr in a chroot has some serious problems
# with feisty and gutsy.
type=xnest

title="$distro ($arch)"
echo "Starting embedded server for $title ..."
if [ "$type" = xnest ]; then
	Xnest -display :0 -geometry 1024x768 -name "$title" $USE &
else
	DISPLAY=:0 Xephyr -screen 1024x768 $USE &
fi

dbus=1
if [ "$distro" = Dapper ]; then
	dbus=
fi

if [ "$dbus" = 1 ]; then
	DISPLAY=$USE /usr/bin/dbus-launch --exit-with-session gnome-session
else
	DISPLAY=$USE gnome-session
fi

# Terminate the X server.
kill %1

# And wait for internal GNOME programs to shut down.
echo
echo "Politely waiting on gnome..."
sleep 30s
