
/**************************************************************************
 *                                                                        *
 *  Regina - A Normal Surface Theory Calculator                           *
 *  CORBA Interface Definition                                            *
 *                                                                        *
 *  Copyright (c) 1999-2001, Ben Burton                                   *
 *  For further details contact Ben Burton (benb@acm.org).                *
 *                                                                        *
 *  This program is free software; you can redistribute it and/or         *
 *  modify it under the terms of the GNU General Public License as        *
 *  published by the Free Software Foundation; either version 2 of the    *
 *  License, or (at your option) any later version.                       *
 *                                                                        *
 *  This program is distributed in the hope that it will be useful, but   *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *  General Public License for more details.                              *
 *                                                                        *
 *  You should have received a copy of the GNU General Public             *
 *  License along with this program; if not, write to the Free            *
 *  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,        *
 *  MA 02111-1307, USA.                                                   *
 *                                                                        *
 **************************************************************************/

/* end stub */

#ifndef __NNORMALSURFACE_IDL
#define __NNORMALSURFACE_IDL

#include "ShareableObject.idl"
#include "Triangulation/NTriangulation.idl"

module Regina {
    module Surfaces {
        interface NNormalSurface : ShareableObject {
            string getTriangleCoord(in long tetIndex, in long vertex);
            string getQuadCoord(in long tetIndex, in long quadType);
            string getOctCoord(in long tetIndex, in long octType);
            string getEdgeWeight(in long edgeIndex);
            string getFaceArcs(in long faceIndex, in long faceVertex);

            long getNumberOfCoords();
            Regina::Triangulation::NTriangulation getTriangulation();

            boolean isCompact();
            string getEulerCharacteristic();
            long isOrientable();
            long isTwoSided();
            long isConnected();
            boolean hasRealBoundary();
            boolean isVertexLinking();
            boolean isSplitting();

            Regina::Triangulation::NTriangulation cutAlong();
            Regina::Triangulation::NTriangulation crush();
        };
    };
};

#endif

