.TH REGINA-ENGINE-CONFIG 1 "September 20, 2016"
.SH NAME
regina-engine-config - get information about the installed version of Regina
.SH SYNOPSIS
.B regina-engine-config
[\fB\-\-prefix\fP[=\fIDIR\fP]]
[\fB\-\-exec\-prefix\fP[=\fIDIR\fP]]
[\fB\-\-version\fP]
[\fB\-\-libs\fP]
[\fB\-\-cflags\fP]
.SH DESCRIPTION
.PP
\fIregina-engine-config\fP tells you which compiler and linker flags should
be used to build the mathematical engine of Regina into your own programs.
Regina's mathematical engine is in the library \fIlibregina-engine.so\fP.
.PP
Regina is a software package for studying 3-manifold triangulations and
normal surfaces. Other key features include angle structures, census
enumeration, combinatorial recognition of triangulations, and high-level
tasks such as 3-sphere recognition and connected sum decomposition.
.SH OPTIONS
\fIregina-engine-config\fP accepts the following options.
.TP
\fB\-\-prefix\fP=\fIDIR\fP
Use DIR instead of the installation prefix that Regina
was built with when computing the output for the \-\-cflags and
\-\-libs options. This option is also used for the exec prefix
if \-\-exec\-prefix is not specified.  This option must be specified
before any \-\-libs or \-\-cflags options.
If no DIR is specified then the current installation prefix will be
written to standard output.

Most people will not need this option.
.TP
\fB\-\-exec\-prefix\fP=\fIDIR\fP
Use DIR instead of the installation exec prefix that
Regina was built with when computing the output for the \-\-cflags
and \-\-libs options.  This option must be specified before any
\-\-libs or \-\-cflags options.
If no DIR is specified then the current installation exec prefix will be
written to standard output.

Most people will not need this option.
.TP
.B \-\-version
Print the currently installed version of Regina.
.TP
.B \-\-libs
Print the linker flags that are required to link a program against
the Regina calculation engine.
.TP
.B \-\-cflags
Print the compiler flags that are required to compile a program that
uses the Regina calculation engine.
.SH SEE ALSO
Regina includes a detailed users' handbook, which may be accessed
through Regina's help menu or read online at
\fIhttp://regina-normal.github.io/\fP .
.SH AUTHOR
This utility was written by Ben Burton <bab@maths.uq.edu.au>,
and is licensed under the GNU General Public License.
Many people have been involved in the development of Regina; see the
users' handbook for a full list of acknowledgements.
.PP
This script regina-engine-config and its manual page were modified from
\fIgtk-config\fP, which contains the following notice:
.PP
.RS
Copyright \(co  1998 Owen Taylor
.PP
Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
.RE
.PP
Note that the permission statement above applies only to regina-engine-config,
and not to Regina as a whole.
