.TH REGINA-ENGINE-CONFIG 1 "22 June 2023" "" "Regina Development Files"
.SH NAME
regina-engine-config - get information about the installed version of Regina
.SH SYNOPSIS
.B regina-engine-config
[\fB\-\-prefix\fP]
[\fB\-\-version\fP]
[\fB\-\-cflags\fP]
[\fB\-\-libs\fP]
.SH DESCRIPTION
.PP
\fIregina-engine-config\fP tells you which compiler and linker flags should
be used to build the mathematical engine of Regina into your own programs.
Regina's mathematical engine is in the library \fIlibregina-engine.so\fP.
.PP
Regina is a software package for 3-manifold and 4-manifold topologists,
with a focus on triangulations, knots and links, normal surfaces, and
angle structures.
.PP
For 3-manifolds, it includes high-level tasks such as 3-sphere recognition,
connected sum decomposition and Hakenness testing, comes with a rich
database of census manifolds, and incorporates the SnapPea kernel for
working with hyperbolic manifolds.  For 4-manifolds, it offers a range of
combinatorial and algebraic tools, plus support for normal hypersurfaces.
For knots and links, Regina can perform combinatorial manipulation,
compute knot polynomials, and work with several import/export formats.
.SH OPTIONS
\fIregina-engine-config\fP accepts the following options.
.TP
\fB\-\-prefix\fP
Prints the installation prefix where Regina has been installed.
.TP
.B \-\-version
Print the currently installed version of Regina.
This will include any BUILD_INFO string that was set when Regina was built.
.TP
.B \-\-cflags
Print the compiler flags that are required to compile a program that
uses the Regina calculation engine.
.TP
.B \-\-libs
Print the linker flags that are required to link a program against
the Regina calculation engine.
.SH SEE ALSO
Regina includes a detailed users' handbook, which may be accessed
through Regina's help menu or read online at
\fIhttp://regina-normal.github.io/\fP .
.SH AUTHOR
This utility was written by Ben Burton <bab@maths.uq.edu.au>,
and is licensed under the GNU General Public License.
Many people have been involved in the development of Regina; see the
users' handbook for a full list of acknowledgements.
.PP
This script regina-engine-config and its manual page were long ago based on
\fIgtk-config\fP, though very little of that remains nowadays.  The original
\fIgtk-config\fP was Copyright \(co  1998 Owen Taylor and used an MIT-style
license; see the regina-engine-config script for full details.
