.TH "REGINA-KDE" "1" "31 March 2012" "" "Regina"

.SH NAME
regina-kde \- Obsolete command for Regina's graphical user interface
.SH SYNOPSIS

\fBregina-gui\fR ...

.SH "DESCRIPTION"
.PP
Regina's graphical user interface has been renamed to \fBregina-gui\fR\&.
.PP
The old command \fBregina-kde\fR\& is now obsolete.  Please update any
shortcuts or scripts accordingly.
.PP
Regina is a software package for studying 3-manifold triangulations
and normal surfaces.  Other key features include
angle structures, census enumeration, combinatorial
recognition of triangulations, and high-level tasks such as
3-sphere recognition and connected sum decomposition.
Regina comes with a full graphical user interface, and also offers
Python bindings and a low-level C++ programming interface.
.PP
.SH "SEE ALSO"
.PP
regina-gui\&.
