#!/bin/bash
#
# Regina - A Normal Surface Theory Calculator
# Makefile recreation utility
#
# Copyright (c) 2005-2006, Ben Burton
# For further details contact Ben Burton (bab@debian.org).
#
# Usage: recreate_makefile
#
# Creates (or recreates) Makefile.in and Makefile within this directory
# and its mpi/ subdirectory.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.
#

set -e

# Variables for this particular instance of recreate_makefile:
reldir=utils/local
relparent=../..

# Move into the correct top-level directory.
absdir="`dirname "$0"`"
absparent="$absdir/$relparent"

# Did we find the top-level source directory?
cd "$absparent"

if ! test -d admin; then
  echo "ERROR: The top-level source directory could not be found." 1>&2
  echo "ERROR: Please contact the author of this software for assistance." 1>&2
  exit 1
fi

# Do it.

am2in() {
  path=$1
  if test "$path.am" -nt "$path.in"; then
    echo "Creating $path.in ..."
    automake "$path"
    echo "Postprocessing $path.in ..."
    perl admin/am_edit "$path.in"
  fi
}

in2mk() {
  path=$1
  if test "$path.in" -nt "$path"; then
    echo "Creating $path ..."
    CONFIG_FILES="$path" CONFIG_HEADERS= ./config.status
  fi
}

am2in "$reldir/Makefile"
am2in "$reldir/mpi/Makefile"

in2mk "$reldir/Makefile"
in2mk "$reldir/mpi/Makefile"

echo "Done."
exit 0
