#!/bin/sh
#
# Boost.Python multi-threading checker for Regina.
#
# Ensures that the compiled python module regina.so links against the
# multi-threaded Boost.Python, not the single-threaded Boost.Python.
#
# For use during the final stage of the debian package build.
#
set -e

tmp=debian/tmp
python_lib=/usr/lib/regina-normal/python/regina.so

echo "Checking Boost.Python multi-threading..."

boost_libname=`ldd $tmp$python_lib | grep 'libboost_python.*\.so' | \
  sed -e 's/^.*\(libboost_python.*\.so\(\.[^ ]\+\)\?\) => .*$/\1/'`

case "$boost_libname" in
  libboost_python*-mt-* )
    # Okay; this looks like the multi-threaded version.
    exit 0
    ;;
  libboost_python*-mt.* )
    # This also looks like the multi-threaded version.
    exit 0
    ;;
  libboost_python*-st-* )
    # Um.  Single-threaded.
    echo "ERROR: You are linking against the single-threaded Boost.Python."
    echo "       You should be using the multi-threaded Boost.Python instead."
    echo "       Your library appears to be $boost_libname."
    exit 1
    ;;
  libboost_python*-st.* )
    # Likewise.
    echo "ERROR: You are linking against the single-threaded Boost.Python."
    echo "       You should be using the multi-threaded Boost.Python instead."
    echo "       Your library appears to be $boost_libname."
    exit 1
    ;;
  libboost_python* )
    # Can't tell.
    echo "ERROR: I cannot tell whether you are linking against the "
    echo "       single-threaded or the multi-threaded Boost.Python."
    echo "       Your library appears to be $boost_libname."
    exit 1
    ;;
  * )
    # Can't even find the library.
    echo "ERROR: I cannot tell which Boost.Python library you are using."
    echo "       The only information I have is: $boost_libname."
    exit 1
    ;;
esac

# Woooh, should never get this far.
echo "ERROR: Control flow error in the Boost.Python checker script."
exit 1
