#!/bin/sh
# CVS utility script for Regina.
# Regenerates ../configure.ac.
#
# This script should NOT be run directly; to use it run "make -f Makefile.cvs"
# from the top-level source directory (the directory above this).

set -e

# Are we in the top-level source directory?

if ! test -d admin; then
  echo "This script should not be run directly." 1>&2
  echo "To use it, run \"make -f Makefile.cvs\" from the top-level" 1>&2
  echo "source directory." 1>&2
  exit 1
fi

real=configure.ac
output=configure.ac.tmp

echo "Regenerating $real:"

# Actually generate the new file.

cat > "$output" <<EOF
dnl
dnl    DO NOT EDIT THIS FILE DIRECTLY.
dnl    It has been automatically generated by Makefile.cvs.
dnl    Try editing configure.ac.top or configure.ac.bot instead.
EOF

cat configure.ac.top >> "$output"

echo "# List of Makefiles (automatically generated by Makefile.cvs):" \
  >> "$output"
for i in `find . -name Makefile.am | sort | sed -e 's#^./##;s#\.am$##'`; do
  case "$i" in
    ./Makefile )
      echo "AC_CONFIG_FILES([Makefile])" >> "$output"
    ;;
    * )
      echo "AC_CONFIG_FILES([$i])" >> "$output"
    ;;
  esac
done

cat configure.ac.bot >> "$output"

# Did configure.ac change?

real=configure.ac

if test -e "$real"; then
  if diff "$output" "$real" > /dev/null; then
    echo "File $real is unchanged."
    rm -f "$output"
  else
    echo "File $real has changed."
    rm -f "$real"
    mv "$output" "$real"
  fi
else
  echo "File $real is new."
  mv "$output" "$real"
fi

