
# Sets $(dirs_idl) to a list of all directories containing IDL files
# describing the interfaces offered by the calculation engine CORBA server.
#
# All locations must be relative to the PARENT directory.
#
# All variables must be exported for use in child makefiles.

export dirs_idl = \
	idl/Algebra \
	idl/File \
	idl/Maths \
	idl/Packet \
	idl/Progress \
	idl/Triangulation \
	idl/Subcomplex \
	idl/Surfaces \
	idl

