#!/bin/sh
# Script include file for regina.
# Provides miscellaneous functions and variables.

# Begin guard
if [ "$read_regscript_misc" != 1 ]; then
read_regscript_misc=1

# ---------- Constants ----------

# Classpath separator.
# This should be ":" under linux/unix environments and ";" under windows.
if [ "$OSTYPE" = "cygwin" ]; then
    cps=";"
else
    cps=":"
fi

# Address to which questions should be emailed.
support="regina-user@lists.sourceforge.net"

# ---------- Functions ----------

# Test whether the given variable has one of the given values.
# Usage: testvalue <value> <variable_name> <value1> [ <value2> ... ]
# Return: 0 if the variable has one of the given values, 1 otherwise.
testvalue () {
    value="$1"
    variable_name="$2"
    list=""
    shift 2
    for v do
        if [ "$value" = "$v" ]; then
            return 0
        fi
        list="$list \"$v\""
    done
    warn "Warning: Variable \$$variable_name was set to \"$value\"."
    warn "         It must be one of:$list"
    return 1
}

# ---------- Environment Variable Defaults ----------

# --- Verbosity ---

# Use default if nothing is specified.
default_verbosity=1
if [ -z "$REGINA_VERBOSITY" ]; then
    export REGINA_VERBOSITY=1
fi

# Check it's an appropriate value.
case "$REGINA_VERBOSITY" in
    [012] )
    ;;
    * )
        error "Error: \$REGINA_VERBOSITY should be 0, 1 or 2."
        error "       (0 = errors, 1 = errors/warnings, 2 = everything)"
        exit 1
    ;;
esac

# ---------- Export current variables ----------

info "-- Verbosity level (REGINA_VERBOSITY): $REGINA_VERBOSITY"
export REGINA_VERBOSITY

# End guard
fi
