#!/bin/sh
#
# Python version checker for Regina.
#
# Ensures that python versions are consistent between the binaries
# (specifically, the compiled python module regina.so) and the
# regina-python startup script.
#
# For use during the final stage of the debian package build.
#
set -e

tmp=debian/tmp
python_script=/usr/bin/regina-python
python_script_src=python/regina-python
python_lib=/usr/lib/regina-normal/python/regina.so

echo "Checking python versions..."

pyver_script=`grep 'python[0-9]\.[0-9]' $tmp$python_script | \
  sed -e 's/^.*python\([0-9]\.[0-9]\).*$/\1/'`

pyver_lib=`ldd $tmp$python_lib | grep 'libpython[0-9]\.[0-9]\.so' | \
  sed -e 's/^.*libpython\([0-9]\.[0-9]\).so.*$/\1/'`

case "$pyver_script" in
  ?.? )
    # Okay; we expect something of the form X.Y.
    ;;
  * )
    echo "ERROR: Could not determine the python version used in $python_script."
    exit 1
    ;;
esac

case "$pyver_lib" in
  ?.? )
    # Okay; we expect something of the form X.Y.
    ;;
  * )
    echo "ERROR: Could not determine the python version used in $python_lib."
    exit 1
    ;;
esac

if ! test "$pyver_script" = "$pyver_lib"; then
  echo
  echo "ERROR: Mismatched python versions between binaries and startup script."
  echo
  echo "       $python_script uses python$pyver_script."
  echo "       $python_lib uses python$pyver_lib."
  echo
  echo "       This can be fixed in the sources by changing the python version "
  echo "           number in $python_script_src and $python_script_src.in"
  echo "           (find the section where \$which_python is initialised)."
  exit 1
fi

exit 0
