#!/bin/bash

# Enable job control, so that the final 'fg' does what it should.
set -m

arch=`uname -m`

if [ -e /etc/issue ]; then
	os=`cat /etc/issue`
elif [ -e /etc/release ]; then
	os=`cat /etc/release`
else
	os=Unknown
fi

# Find a free display number.
for i in `seq 100`; do
	if [ ! -e "/tmp/.X$i-lock" ]; then break; fi
	i=$(($i+1))
done
if [ -e "/tmp/.X$i-lock" ]; then
	echo "ERROR: Could not find a free display number."
	echo "       Try removing some stale X lock files from /tmp."
	exit 1
fi

USE=:$i
echo "Using display $USE."

kde=
dbus=
exitwait=
case "$os" in
	Ubuntu\ 6.06* )
		distro=Dapper
		exitwait=1
		;;
	Ubuntu\ 7.04* )
		distro=Feisty
		dbus=1
		exitwait=1
		;;
	Ubuntu\ 7.10* )
		distro=Gutsy
		dbus=1
		exitwait=1
		;;
	Debian\ GNU/Linux\ */sid\ * )
		distro=Sid
		kde=1
		;;
	Mandriva\ Linux\ release\ 2007.0\ * )
		distro="Mandriva 2007.0"
		exitwait=1
		kde=1
		;;
	* )
		distro=Unknown
		exitwait=1
		kde=1
		;;
esac

# Use Xnest in most cases; Xephyr in a chroot has some serious problems
# with ubuntu feisty and gutsy.
type=xnest

if [ "$distro" = Sid ]; then
	type=xephyr
fi

title="$distro ($arch)"
echo "Starting embedded server for $title ..."
if [ "$type" = xnest ]; then
	Xnest -display :0 -geometry 1024x768 -name "$title" $USE &
else
	DISPLAY=:0 Xephyr -screen 1024x768 $USE &
fi

if [ "$kde" = 1 ]; then
	session=startkde
else
	session=gnome-session
fi

if [ "$dbus" = 1 ]; then
	DISPLAY=$USE /usr/bin/dbus-launch --exit-with-session "$session"
else
	DISPLAY=$USE "$session"
fi

# Terminate the X server.
kill %1

# And wait for internal GNOME programs to shut down.
if [ "$exitwait" = 1 ]; then
	echo
	echo "Politely waiting on daemons to shut down..."
	sleep 45s
fi
