macro(cdr var junk)
  set(${var} ${ARGN})
endmacro(cdr)

macro(extra_dist place)
  if(EXTRA_DIST_SET)
    set(place ${ARGV1})
    cdr(files ${ARGV})
    string(REGEX REPLACE ${CMAKE_SOURCE_DIR} "" ii ${CMAKE_CURRENT_SOURCE_DIR})
    string(REGEX REPLACE ^/ "" iii ${ii})
    foreach(i ${files})
      message( "install(${place} ${i} DESTINATION share/regina/${iii})")
    endforeach(i)
  endif(EXTRA_DIST_SET)
endmacro(extra_dist)
