# TODO Insert GPL licence bits

FIND_PATH(GMP_INCLUDE_DIR gmp.h "/usr/include" "/usr/local/include")

FIND_LIBRARY(GMP_LIBRARY NAMES gmp PATH "/usr/lib" "/usr/local/lib")

IF(GMP_INCLUDE_DIR AND GMP_LIBRARY)
  SET(GMP_FOUND TRUE)
ENDIF(GMP_INCLUDE_DIR AND GMP_LIBRARY)

IF(GMP_FOUND)
  IF (NOT GMP_FIND_QUIETLY)
    MESSAGE(STATUS "Found gmp: ${GMP_LIBRARY}")
  ENDIF (NOT GMP_FIND_QUIETLY)
ELSE (GMP_FOUND)
  IF (GMP_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find gmp")
  ENDIF (GMP_FIND_REQUIRED)
ENDIF(GMP_FOUND)
