#!/usr/bin/python
#
# Regina - A Normal Surface Theory Calculator
# Alternate implementation of the censuslookup command-line utility
#
# Copyright (c) 2002-2016, Ben Burton
# For further details contact Ben Burton (bab@debian.org).
#
# This implementation is designed for the Xcode bundle only - it hard-codes
# paths to the census databases that are specific to the bundle layout.
# In all other settings, you should use the standard implementation
# of censuslookup from the utils/ directory of Regina's source tree.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# As an exception, when this program is distributed through (i) the
# App Store by Apple Inc.; (ii) the Mac App Store by Apple Inc.; or
# (iii) Google Play by Google Inc., then that store may impose any
# digital rights management, device limits and/or redistribution
# restrictions that are required by its terms of service.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.

import os
import sys

def usage(error):
    if error:
        sys.stderr.write(error + '\n\n')

    sys.stderr.write('Usage:\n')
    sys.stderr.write('    ' + sys.argv[0] + ' <isosig> ...\n')
    sys.exit(1)

if len(sys.argv) < 2:
    usage('Please specify one or more isomorphism signatures.')

appDir = os.path.dirname(sys.argv[0])

try:
    sys.path = [ appDir + '/python' ] + sys.path
    import regina
except:
    sys.stderr.write('ERROR: Could not import the regina module.\n')
    sys.exit(1)

regina.NGlobalDirs.setDirs('', '', appDir + '/../Resources')

for sig in sys.argv[1:]:
    hits = regina.NCensus.lookup(sig)

    n = hits.count()
    if n == 1:
        print sig + ': 1 hit'
    else:
        print sig + ':', n, 'hits'

    hit = hits.first()
    while hit:
        print '    ' + hit.name() + ' -- ' + hit.db().desc()
        hit = hit.next()

    print
